#!/usr/bin/env node
// OTUS capture transcript filter — normalized transcript contract v1 (Claude Code side).
//
// Why this exists
// ---------------
// `.otus/capture.sh` used to POST the raw Claude Code session `.jsonl` verbatim.
// A real session measured 214 lines / 498 KB, of which only ~20 KB (4%) was the
// thing capture exists to show an instructor: what the student typed and what the
// agent said back. The other 96% was `attachment` blobs, duplicated tool results
// (the `tool_result` content block AND the `toolUseResult` field carry the same
// bytes), and per-turn bookkeeping (`queue-operation`, `last-prompt`,
// `atis-latch`, `mode`, `system`).
//
// That cost twice: storage on every Stop-hook POST of a growing session, and
// reviewability — reading one capture back meant digging the ~4% of signal out by
// hand every single time.
//
// This filter emits the normalized contract below. The Codex adapter
// (`.otus/capture-codex.mjs`, generated by OTUS `provisionLogic.ts`) emits the
// SAME shape from Codex's own event stream, so an instructor reading a capture
// sees one format regardless of which agent the student used. Keep the two in
// step: a field added here should be added there.
//
// Normalized transcript contract v1
// ---------------------------------
//   {
//     source_tool: "claude" | "codex",
//     index:       <n>,                  // position in the FILTERED stream
//     role:        "user" | "assistant" | "reasoning" | "tool_call" | "tool_result",
//     text:        "...",                // already truncated per the caps below
//     timestamp:   "..." | null,
//     tool_name:   "Read",               // tool_call / tool_result only
//     truncated:   true                  // only when `text` was cut
//   }
//
// The server contract is unchanged: `deliverable-capture` takes
// `transcript: unknown[]` and is source-agnostic, so this needs no edge-fn deploy.
//
// Fail-open, like every other hook script here: any error exits non-zero with no
// stdout, and capture.sh falls back to POSTing the raw transcript. Capture is
// observation only and must never block or slow the student's turn.

import { readFile } from "node:fs/promises";

// Truncation caps. Prose is what coaching reads, so it gets room; tool traffic
// only needs to show WHAT ran and whether it worked, not its full payload.
const TEXT_CAP = 10000; // user / assistant prose
const REASONING_CAP = 2000; // extended-thinking blocks
const TOOL_CAP = 500; // tool call input, tool result output
const TOTAL_CAP = 1000000; // hard ceiling on total emitted text

// A user turn that is nothing but injected context is machinery, not something
// the student typed. Matched only when the text STARTS with the tag, so a real
// prompt that happens to quote one is kept.
const INJECTED_PREFIXES = [
  "<system-reminder>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<local-command-caveat>",
  "<command-message>",
  "<command-name>",
  "<command-args>",
  // Harness envelopes that arrive on the user turn but are explicitly not the
  // student: subagent completions, external wakes, relayed third-party content.
  "<task-notification>",
  "<wake",
  "<untrusted_external_data",
];

function isInjectedContext(text) {
  const trimmed = text.trimStart();
  return INJECTED_PREFIXES.some((tag) => trimmed.startsWith(tag));
}

/** Flatten Claude's several content shapes (string, block array, nested) to text. */
function textFrom(value) {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.map(textFrom).filter(Boolean).join("\n");
  if (value && typeof value === "object") {
    if (typeof value.text === "string") return value.text;
    if (typeof value.content === "string") return value.content;
    if (value.content) return textFrom(value.content);
  }
  return "";
}

export function filterClaudeTranscript(raw) {
  const events = [];
  let spent = 0;
  let capped = false;

  const push = (role, text, timestamp, cap, toolName) => {
    if (capped) return;
    const body = String(text ?? "").trim();
    if (!body) return;
    if (spent >= TOTAL_CAP) {
      capped = true;
      events.push({
        source_tool: "claude",
        index: events.length,
        role: "system",
        text: "[OTUS capture: transcript truncated at the size cap; earlier turns are complete.]",
        timestamp: null,
      });
      return;
    }
    const clipped = body.length > cap;
    const event = {
      source_tool: "claude",
      index: events.length,
      role,
      text: clipped ? body.slice(0, cap) : body,
      timestamp: timestamp ?? null,
    };
    if (toolName) event.tool_name = toolName;
    if (clipped) event.truncated = true;
    spent += event.text.length;
    events.push(event);
  };

  for (const line of String(raw).split(/\r?\n/)) {
    if (!line.trim()) continue;
    let entry;
    try {
      entry = JSON.parse(line);
    } catch {
      continue; // A torn final line mid-write is normal; skip it.
    }

    // Everything that is not a conversation turn is bookkeeping: `attachment`,
    // `queue-operation`, `last-prompt`, `atis-latch`, `mode`, `system`.
    const type = entry?.type;
    if (type !== "user" && type !== "assistant") continue;
    if (entry?.isMeta) continue;

    const timestamp = entry?.timestamp ?? null;
    const content = entry?.message?.content;

    if (typeof content === "string") {
      if (!isInjectedContext(content)) push("user", content, timestamp, TEXT_CAP);
      continue;
    }
    if (!Array.isArray(content)) continue;

    for (const block of content) {
      switch (block?.type) {
        case "text": {
          const text = String(block.text ?? "");
          if (type === "user" && isInjectedContext(text)) break;
          push(type === "user" ? "user" : "assistant", text, timestamp, TEXT_CAP);
          break;
        }
        case "thinking":
          // Claude Code persists these with an EMPTY `thinking` and a ~500-char
          // `signature`, so in practice this emits nothing and the signature
          // bytes (30 KB in the session this was measured on) are dropped. Kept
          // because the contract has a `reasoning` role the Codex side does fill.
          push("reasoning", block.thinking, timestamp, REASONING_CAP);
          break;
        case "tool_use":
          push("tool_call", JSON.stringify(block.input ?? {}), timestamp, TOOL_CAP, block.name);
          break;
        case "tool_result":
          // `entry.toolUseResult` carries these same bytes again — never emitted.
          push("tool_result", textFrom(block.content), timestamp, TOOL_CAP);
          break;
        default:
          break;
      }
    }
  }

  return events;
}

async function main() {
  const transcriptPath = process.argv[2];
  if (!transcriptPath) throw new Error("usage: capture-filter.mjs <transcript-path>");
  const events = filterClaudeTranscript(await readFile(transcriptPath, "utf8"));
  if (events.length === 0) throw new Error("no conversation turns in transcript");
  process.stdout.write(JSON.stringify(events));
}

// Only run when invoked directly, so tests can import the filter.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    process.stderr.write(String(error?.message ?? error) + "\n");
    process.exitCode = 1;
  });
}
